/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDepoRouteImport } from './routes/_authenticated/depo'
import { Route as AuthenticatedKayitlarRouteImport } from './routes/_authenticated/kayitlar'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedSiparislerRouteImport } from './routes/_authenticated/siparisler'
import { Route as AuthenticatedAdminIstasyonlarRouteImport } from './routes/_authenticated/admin/istasyonlar'
import { Route as AuthenticatedAdminKullanicilarRouteImport } from './routes/_authenticated/admin/kullanicilar'
import { Route as AuthenticatedAdminMusterilerRouteImport } from './routes/_authenticated/admin/musteriler'
import { Route as AuthenticatedSiparisOrderIdRouteImport } from './routes/_authenticated/siparis.$orderId'
import { Route as ApiPublicGrafikTemizlikRouteImport } from './routes/api/public/grafik-temizlik'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDepoRoute = AuthenticatedDepoRouteImport.update({
  id: '/depo',
  path: '/depo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKayitlarRoute = AuthenticatedKayitlarRouteImport.update({
  id: '/kayitlar',
  path: '/kayitlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSiparislerRoute = AuthenticatedSiparislerRouteImport.update({
  id: '/siparisler',
  path: '/siparisler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIstasyonlarRoute =
  AuthenticatedAdminIstasyonlarRouteImport.update({
    id: '/admin/istasyonlar',
    path: '/admin/istasyonlar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKullanicilarRoute =
  AuthenticatedAdminKullanicilarRouteImport.update({
    id: '/admin/kullanicilar',
    path: '/admin/kullanicilar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMusterilerRoute =
  AuthenticatedAdminMusterilerRouteImport.update({
    id: '/admin/musteriler',
    path: '/admin/musteriler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiparisOrderIdRoute =
  AuthenticatedSiparisOrderIdRouteImport.update({
    id: '/siparis/$orderId',
    path: '/siparis/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicGrafikTemizlikRoute = ApiPublicGrafikTemizlikRouteImport.update({
  id: '/api/public/grafik-temizlik',
  path: '/api/public/grafik-temizlik',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/depo': typeof AuthenticatedDepoRoute
  '/kayitlar': typeof AuthenticatedKayitlarRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/siparisler': typeof AuthenticatedSiparislerRoute
  '/admin/istasyonlar': typeof AuthenticatedAdminIstasyonlarRoute
  '/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/admin/musteriler': typeof AuthenticatedAdminMusterilerRoute
  '/siparis/$orderId': typeof AuthenticatedSiparisOrderIdRoute
  '/api/public/grafik-temizlik': typeof ApiPublicGrafikTemizlikRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/depo': typeof AuthenticatedDepoRoute
  '/kayitlar': typeof AuthenticatedKayitlarRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/siparisler': typeof AuthenticatedSiparislerRoute
  '/admin/istasyonlar': typeof AuthenticatedAdminIstasyonlarRoute
  '/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/admin/musteriler': typeof AuthenticatedAdminMusterilerRoute
  '/siparis/$orderId': typeof AuthenticatedSiparisOrderIdRoute
  '/api/public/grafik-temizlik': typeof ApiPublicGrafikTemizlikRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/depo': typeof AuthenticatedDepoRoute
  '/_authenticated/kayitlar': typeof AuthenticatedKayitlarRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/siparisler': typeof AuthenticatedSiparislerRoute
  '/_authenticated/admin/istasyonlar': typeof AuthenticatedAdminIstasyonlarRoute
  '/_authenticated/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/_authenticated/admin/musteriler': typeof AuthenticatedAdminMusterilerRoute
  '/_authenticated/siparis/$orderId': typeof AuthenticatedSiparisOrderIdRoute
  '/api/public/grafik-temizlik': typeof ApiPublicGrafikTemizlikRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/depo'
    | '/kayitlar'
    | '/panel'
    | '/siparisler'
    | '/admin/istasyonlar'
    | '/admin/kullanicilar'
    | '/admin/musteriler'
    | '/siparis/$orderId'
    | '/api/public/grafik-temizlik'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/depo'
    | '/kayitlar'
    | '/panel'
    | '/siparisler'
    | '/admin/istasyonlar'
    | '/admin/kullanicilar'
    | '/admin/musteriler'
    | '/siparis/$orderId'
    | '/api/public/grafik-temizlik'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/depo'
    | '/_authenticated/kayitlar'
    | '/_authenticated/panel'
    | '/_authenticated/siparisler'
    | '/_authenticated/admin/istasyonlar'
    | '/_authenticated/admin/kullanicilar'
    | '/_authenticated/admin/musteriler'
    | '/_authenticated/siparis/$orderId'
    | '/api/public/grafik-temizlik'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGrafikTemizlikRoute: typeof ApiPublicGrafikTemizlikRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/depo': {
      id: '/_authenticated/depo'
      path: '/depo'
      fullPath: '/depo'
      preLoaderRoute: typeof AuthenticatedDepoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kayitlar': {
      id: '/_authenticated/kayitlar'
      path: '/kayitlar'
      fullPath: '/kayitlar'
      preLoaderRoute: typeof AuthenticatedKayitlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/siparisler': {
      id: '/_authenticated/siparisler'
      path: '/siparisler'
      fullPath: '/siparisler'
      preLoaderRoute: typeof AuthenticatedSiparislerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/istasyonlar': {
      id: '/_authenticated/admin/istasyonlar'
      path: '/admin/istasyonlar'
      fullPath: '/admin/istasyonlar'
      preLoaderRoute: typeof AuthenticatedAdminIstasyonlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/kullanicilar': {
      id: '/_authenticated/admin/kullanicilar'
      path: '/admin/kullanicilar'
      fullPath: '/admin/kullanicilar'
      preLoaderRoute: typeof AuthenticatedAdminKullanicilarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/musteriler': {
      id: '/_authenticated/admin/musteriler'
      path: '/admin/musteriler'
      fullPath: '/admin/musteriler'
      preLoaderRoute: typeof AuthenticatedAdminMusterilerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/siparis/$orderId': {
      id: '/_authenticated/siparis/$orderId'
      path: '/siparis/$orderId'
      fullPath: '/siparis/$orderId'
      preLoaderRoute: typeof AuthenticatedSiparisOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/grafik-temizlik': {
      id: '/api/public/grafik-temizlik'
      path: '/api/public/grafik-temizlik'
      fullPath: '/api/public/grafik-temizlik'
      preLoaderRoute: typeof ApiPublicGrafikTemizlikRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDepoRoute: typeof AuthenticatedDepoRoute
  AuthenticatedKayitlarRoute: typeof AuthenticatedKayitlarRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedSiparislerRoute: typeof AuthenticatedSiparislerRoute
  AuthenticatedAdminIstasyonlarRoute: typeof AuthenticatedAdminIstasyonlarRoute
  AuthenticatedAdminKullanicilarRoute: typeof AuthenticatedAdminKullanicilarRoute
  AuthenticatedAdminMusterilerRoute: typeof AuthenticatedAdminMusterilerRoute
  AuthenticatedSiparisOrderIdRoute: typeof AuthenticatedSiparisOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDepoRoute: AuthenticatedDepoRoute,
  AuthenticatedKayitlarRoute: AuthenticatedKayitlarRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedSiparislerRoute: AuthenticatedSiparislerRoute,
  AuthenticatedAdminIstasyonlarRoute: AuthenticatedAdminIstasyonlarRoute,
  AuthenticatedAdminKullanicilarRoute: AuthenticatedAdminKullanicilarRoute,
  AuthenticatedAdminMusterilerRoute: AuthenticatedAdminMusterilerRoute,
  AuthenticatedSiparisOrderIdRoute: AuthenticatedSiparisOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGrafikTemizlikRoute: ApiPublicGrafikTemizlikRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
