/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedArsivRouteImport } from './routes/_authenticated/arsiv'
import { Route as AuthenticatedDepoRouteImport } from './routes/_authenticated/depo'
import { Route as AuthenticatedKaliteRouteImport } from './routes/_authenticated/kalite'
import { Route as AuthenticatedKayitlarRouteImport } from './routes/_authenticated/kayitlar'
import { Route as AuthenticatedKuyrukRouteImport } from './routes/_authenticated/kuyruk'
import { Route as AuthenticatedMuhasebeRouteImport } from './routes/_authenticated/muhasebe'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedSevkiyatRouteImport } from './routes/_authenticated/sevkiyat'
import { Route as AuthenticatedSiparislerRouteImport } from './routes/_authenticated/siparisler'
import { Route as AuthenticatedUretimRouteImport } from './routes/_authenticated/uretim'
import { Route as AuthenticatedAdminIstasyonlarRouteImport } from './routes/_authenticated/admin/istasyonlar'
import { Route as AuthenticatedAdminKullanicilarRouteImport } from './routes/_authenticated/admin/kullanicilar'
import { Route as AuthenticatedAdminMusterilerRouteImport } from './routes/_authenticated/admin/musteriler'
import { Route as AuthenticatedOperatorIndexRouteImport } from './routes/_authenticated/operator/index'
import { Route as AuthenticatedOperatorProvaRouteImport } from './routes/_authenticated/operator/prova'
import { Route as AuthenticatedRotaOrderIdRouteImport } from './routes/_authenticated/rota.$orderId'
import { Route as AuthenticatedSilindirHazirlaOrderIdRouteImport } from './routes/_authenticated/silindir-hazirla.$orderId'
import { Route as AuthenticatedSilindirCylCodeRouteImport } from './routes/_authenticated/silindir.$cylCode'
import { Route as AuthenticatedSiparisOrderIdRouteImport } from './routes/_authenticated/siparis.$orderId'
import { Route as ApiPublicGrafikTemizlikRouteImport } from './routes/api/public/grafik-temizlik'
import { Route as AuthenticatedOperatorAktifOperationIdRouteImport } from './routes/_authenticated/operator/aktif.$operationId'
import { Route as AuthenticatedOperatorIsStepIdRouteImport } from './routes/_authenticated/operator/is.$stepId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArsivRoute = AuthenticatedArsivRouteImport.update({
  id: '/arsiv',
  path: '/arsiv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepoRoute = AuthenticatedDepoRouteImport.update({
  id: '/depo',
  path: '/depo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKaliteRoute = AuthenticatedKaliteRouteImport.update({
  id: '/kalite',
  path: '/kalite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKayitlarRoute = AuthenticatedKayitlarRouteImport.update({
  id: '/kayitlar',
  path: '/kayitlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKuyrukRoute = AuthenticatedKuyrukRouteImport.update({
  id: '/kuyruk',
  path: '/kuyruk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMuhasebeRoute = AuthenticatedMuhasebeRouteImport.update({
  id: '/muhasebe',
  path: '/muhasebe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSevkiyatRoute = AuthenticatedSevkiyatRouteImport.update({
  id: '/sevkiyat',
  path: '/sevkiyat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSiparislerRoute = AuthenticatedSiparislerRouteImport.update({
  id: '/siparisler',
  path: '/siparisler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUretimRoute = AuthenticatedUretimRouteImport.update({
  id: '/uretim',
  path: '/uretim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIstasyonlarRoute =
  AuthenticatedAdminIstasyonlarRouteImport.update({
    id: '/admin/istasyonlar',
    path: '/admin/istasyonlar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKullanicilarRoute =
  AuthenticatedAdminKullanicilarRouteImport.update({
    id: '/admin/kullanicilar',
    path: '/admin/kullanicilar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMusterilerRoute =
  AuthenticatedAdminMusterilerRouteImport.update({
    id: '/admin/musteriler',
    path: '/admin/musteriler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperatorIndexRoute =
  AuthenticatedOperatorIndexRouteImport.update({
    id: '/operator/',
    path: '/operator/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperatorProvaRoute =
  AuthenticatedOperatorProvaRouteImport.update({
    id: '/operator/prova',
    path: '/operator/prova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaOrderIdRoute =
  AuthenticatedRotaOrderIdRouteImport.update({
    id: '/rota/$orderId',
    path: '/rota/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSilindirHazirlaOrderIdRoute =
  AuthenticatedSilindirHazirlaOrderIdRouteImport.update({
    id: '/silindir-hazirla/$orderId',
    path: '/silindir-hazirla/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSilindirCylCodeRoute =
  AuthenticatedSilindirCylCodeRouteImport.update({
    id: '/silindir/$cylCode',
    path: '/silindir/$cylCode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiparisOrderIdRoute =
  AuthenticatedSiparisOrderIdRouteImport.update({
    id: '/siparis/$orderId',
    path: '/siparis/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicGrafikTemizlikRoute = ApiPublicGrafikTemizlikRouteImport.update({
  id: '/api/public/grafik-temizlik',
  path: '/api/public/grafik-temizlik',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperatorAktifOperationIdRoute =
  AuthenticatedOperatorAktifOperationIdRouteImport.update({
    id: '/operator/aktif/$operationId',
    path: '/operator/aktif/$operationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperatorIsStepIdRoute =
  AuthenticatedOperatorIsStepIdRouteImport.update({
    id: '/operator/is/$stepId',
    path: '/operator/is/$stepId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arsiv': typeof AuthenticatedArsivRoute
  '/depo': typeof AuthenticatedDepoRoute
  '/kalite': typeof AuthenticatedKaliteRoute
  '/kayitlar': typeof AuthenticatedKayitlarRoute
  '/kuyruk': typeof AuthenticatedKuyrukRoute
  '/muhasebe': typeof AuthenticatedMuhasebeRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/sevkiyat': typeof AuthenticatedSevkiyatRoute
  '/siparisler': typeof AuthenticatedSiparislerRoute
  '/uretim': typeof AuthenticatedUretimRoute
  '/admin/istasyonlar': typeof AuthenticatedAdminIstasyonlarRoute
  '/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/admin/musteriler': typeof AuthenticatedAdminMusterilerRoute
  '/operator/prova': typeof AuthenticatedOperatorProvaRoute
  '/rota/$orderId': typeof AuthenticatedRotaOrderIdRoute
  '/silindir-hazirla/$orderId': typeof AuthenticatedSilindirHazirlaOrderIdRoute
  '/silindir/$cylCode': typeof AuthenticatedSilindirCylCodeRoute
  '/siparis/$orderId': typeof AuthenticatedSiparisOrderIdRoute
  '/api/public/grafik-temizlik': typeof ApiPublicGrafikTemizlikRoute
  '/operator/': typeof AuthenticatedOperatorIndexRoute
  '/operator/aktif/$operationId': typeof AuthenticatedOperatorAktifOperationIdRoute
  '/operator/is/$stepId': typeof AuthenticatedOperatorIsStepIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arsiv': typeof AuthenticatedArsivRoute
  '/depo': typeof AuthenticatedDepoRoute
  '/kalite': typeof AuthenticatedKaliteRoute
  '/kayitlar': typeof AuthenticatedKayitlarRoute
  '/kuyruk': typeof AuthenticatedKuyrukRoute
  '/muhasebe': typeof AuthenticatedMuhasebeRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/sevkiyat': typeof AuthenticatedSevkiyatRoute
  '/siparisler': typeof AuthenticatedSiparislerRoute
  '/uretim': typeof AuthenticatedUretimRoute
  '/admin/istasyonlar': typeof AuthenticatedAdminIstasyonlarRoute
  '/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/admin/musteriler': typeof AuthenticatedAdminMusterilerRoute
  '/operator/prova': typeof AuthenticatedOperatorProvaRoute
  '/rota/$orderId': typeof AuthenticatedRotaOrderIdRoute
  '/silindir-hazirla/$orderId': typeof AuthenticatedSilindirHazirlaOrderIdRoute
  '/silindir/$cylCode': typeof AuthenticatedSilindirCylCodeRoute
  '/siparis/$orderId': typeof AuthenticatedSiparisOrderIdRoute
  '/api/public/grafik-temizlik': typeof ApiPublicGrafikTemizlikRoute
  '/operator': typeof AuthenticatedOperatorIndexRoute
  '/operator/aktif/$operationId': typeof AuthenticatedOperatorAktifOperationIdRoute
  '/operator/is/$stepId': typeof AuthenticatedOperatorIsStepIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/arsiv': typeof AuthenticatedArsivRoute
  '/_authenticated/depo': typeof AuthenticatedDepoRoute
  '/_authenticated/kalite': typeof AuthenticatedKaliteRoute
  '/_authenticated/kayitlar': typeof AuthenticatedKayitlarRoute
  '/_authenticated/kuyruk': typeof AuthenticatedKuyrukRoute
  '/_authenticated/muhasebe': typeof AuthenticatedMuhasebeRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/sevkiyat': typeof AuthenticatedSevkiyatRoute
  '/_authenticated/siparisler': typeof AuthenticatedSiparislerRoute
  '/_authenticated/uretim': typeof AuthenticatedUretimRoute
  '/_authenticated/admin/istasyonlar': typeof AuthenticatedAdminIstasyonlarRoute
  '/_authenticated/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/_authenticated/admin/musteriler': typeof AuthenticatedAdminMusterilerRoute
  '/_authenticated/operator/prova': typeof AuthenticatedOperatorProvaRoute
  '/_authenticated/rota/$orderId': typeof AuthenticatedRotaOrderIdRoute
  '/_authenticated/silindir-hazirla/$orderId': typeof AuthenticatedSilindirHazirlaOrderIdRoute
  '/_authenticated/silindir/$cylCode': typeof AuthenticatedSilindirCylCodeRoute
  '/_authenticated/siparis/$orderId': typeof AuthenticatedSiparisOrderIdRoute
  '/api/public/grafik-temizlik': typeof ApiPublicGrafikTemizlikRoute
  '/_authenticated/operator/': typeof AuthenticatedOperatorIndexRoute
  '/_authenticated/operator/aktif/$operationId': typeof AuthenticatedOperatorAktifOperationIdRoute
  '/_authenticated/operator/is/$stepId': typeof AuthenticatedOperatorIsStepIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/arsiv'
    | '/depo'
    | '/kalite'
    | '/kayitlar'
    | '/kuyruk'
    | '/muhasebe'
    | '/panel'
    | '/sevkiyat'
    | '/siparisler'
    | '/uretim'
    | '/admin/istasyonlar'
    | '/admin/kullanicilar'
    | '/admin/musteriler'
    | '/operator/prova'
    | '/rota/$orderId'
    | '/silindir-hazirla/$orderId'
    | '/silindir/$cylCode'
    | '/siparis/$orderId'
    | '/api/public/grafik-temizlik'
    | '/operator/'
    | '/operator/aktif/$operationId'
    | '/operator/is/$stepId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/arsiv'
    | '/depo'
    | '/kalite'
    | '/kayitlar'
    | '/kuyruk'
    | '/muhasebe'
    | '/panel'
    | '/sevkiyat'
    | '/siparisler'
    | '/uretim'
    | '/admin/istasyonlar'
    | '/admin/kullanicilar'
    | '/admin/musteriler'
    | '/operator/prova'
    | '/rota/$orderId'
    | '/silindir-hazirla/$orderId'
    | '/silindir/$cylCode'
    | '/siparis/$orderId'
    | '/api/public/grafik-temizlik'
    | '/operator'
    | '/operator/aktif/$operationId'
    | '/operator/is/$stepId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/arsiv'
    | '/_authenticated/depo'
    | '/_authenticated/kalite'
    | '/_authenticated/kayitlar'
    | '/_authenticated/kuyruk'
    | '/_authenticated/muhasebe'
    | '/_authenticated/panel'
    | '/_authenticated/sevkiyat'
    | '/_authenticated/siparisler'
    | '/_authenticated/uretim'
    | '/_authenticated/admin/istasyonlar'
    | '/_authenticated/admin/kullanicilar'
    | '/_authenticated/admin/musteriler'
    | '/_authenticated/operator/prova'
    | '/_authenticated/rota/$orderId'
    | '/_authenticated/silindir-hazirla/$orderId'
    | '/_authenticated/silindir/$cylCode'
    | '/_authenticated/siparis/$orderId'
    | '/api/public/grafik-temizlik'
    | '/_authenticated/operator/'
    | '/_authenticated/operator/aktif/$operationId'
    | '/_authenticated/operator/is/$stepId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGrafikTemizlikRoute: typeof ApiPublicGrafikTemizlikRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/arsiv': {
      id: '/_authenticated/arsiv'
      path: '/arsiv'
      fullPath: '/arsiv'
      preLoaderRoute: typeof AuthenticatedArsivRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depo': {
      id: '/_authenticated/depo'
      path: '/depo'
      fullPath: '/depo'
      preLoaderRoute: typeof AuthenticatedDepoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalite': {
      id: '/_authenticated/kalite'
      path: '/kalite'
      fullPath: '/kalite'
      preLoaderRoute: typeof AuthenticatedKaliteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kayitlar': {
      id: '/_authenticated/kayitlar'
      path: '/kayitlar'
      fullPath: '/kayitlar'
      preLoaderRoute: typeof AuthenticatedKayitlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kuyruk': {
      id: '/_authenticated/kuyruk'
      path: '/kuyruk'
      fullPath: '/kuyruk'
      preLoaderRoute: typeof AuthenticatedKuyrukRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/muhasebe': {
      id: '/_authenticated/muhasebe'
      path: '/muhasebe'
      fullPath: '/muhasebe'
      preLoaderRoute: typeof AuthenticatedMuhasebeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sevkiyat': {
      id: '/_authenticated/sevkiyat'
      path: '/sevkiyat'
      fullPath: '/sevkiyat'
      preLoaderRoute: typeof AuthenticatedSevkiyatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/siparisler': {
      id: '/_authenticated/siparisler'
      path: '/siparisler'
      fullPath: '/siparisler'
      preLoaderRoute: typeof AuthenticatedSiparislerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/uretim': {
      id: '/_authenticated/uretim'
      path: '/uretim'
      fullPath: '/uretim'
      preLoaderRoute: typeof AuthenticatedUretimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/istasyonlar': {
      id: '/_authenticated/admin/istasyonlar'
      path: '/admin/istasyonlar'
      fullPath: '/admin/istasyonlar'
      preLoaderRoute: typeof AuthenticatedAdminIstasyonlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/kullanicilar': {
      id: '/_authenticated/admin/kullanicilar'
      path: '/admin/kullanicilar'
      fullPath: '/admin/kullanicilar'
      preLoaderRoute: typeof AuthenticatedAdminKullanicilarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/musteriler': {
      id: '/_authenticated/admin/musteriler'
      path: '/admin/musteriler'
      fullPath: '/admin/musteriler'
      preLoaderRoute: typeof AuthenticatedAdminMusterilerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator/': {
      id: '/_authenticated/operator/'
      path: '/operator'
      fullPath: '/operator/'
      preLoaderRoute: typeof AuthenticatedOperatorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator/prova': {
      id: '/_authenticated/operator/prova'
      path: '/operator/prova'
      fullPath: '/operator/prova'
      preLoaderRoute: typeof AuthenticatedOperatorProvaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/$orderId': {
      id: '/_authenticated/rota/$orderId'
      path: '/rota/$orderId'
      fullPath: '/rota/$orderId'
      preLoaderRoute: typeof AuthenticatedRotaOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/silindir-hazirla/$orderId': {
      id: '/_authenticated/silindir-hazirla/$orderId'
      path: '/silindir-hazirla/$orderId'
      fullPath: '/silindir-hazirla/$orderId'
      preLoaderRoute: typeof AuthenticatedSilindirHazirlaOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/silindir/$cylCode': {
      id: '/_authenticated/silindir/$cylCode'
      path: '/silindir/$cylCode'
      fullPath: '/silindir/$cylCode'
      preLoaderRoute: typeof AuthenticatedSilindirCylCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/siparis/$orderId': {
      id: '/_authenticated/siparis/$orderId'
      path: '/siparis/$orderId'
      fullPath: '/siparis/$orderId'
      preLoaderRoute: typeof AuthenticatedSiparisOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/grafik-temizlik': {
      id: '/api/public/grafik-temizlik'
      path: '/api/public/grafik-temizlik'
      fullPath: '/api/public/grafik-temizlik'
      preLoaderRoute: typeof ApiPublicGrafikTemizlikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operator/aktif/$operationId': {
      id: '/_authenticated/operator/aktif/$operationId'
      path: '/operator/aktif/$operationId'
      fullPath: '/operator/aktif/$operationId'
      preLoaderRoute: typeof AuthenticatedOperatorAktifOperationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator/is/$stepId': {
      id: '/_authenticated/operator/is/$stepId'
      path: '/operator/is/$stepId'
      fullPath: '/operator/is/$stepId'
      preLoaderRoute: typeof AuthenticatedOperatorIsStepIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArsivRoute: typeof AuthenticatedArsivRoute
  AuthenticatedDepoRoute: typeof AuthenticatedDepoRoute
  AuthenticatedKaliteRoute: typeof AuthenticatedKaliteRoute
  AuthenticatedKayitlarRoute: typeof AuthenticatedKayitlarRoute
  AuthenticatedKuyrukRoute: typeof AuthenticatedKuyrukRoute
  AuthenticatedMuhasebeRoute: typeof AuthenticatedMuhasebeRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedSevkiyatRoute: typeof AuthenticatedSevkiyatRoute
  AuthenticatedSiparislerRoute: typeof AuthenticatedSiparislerRoute
  AuthenticatedUretimRoute: typeof AuthenticatedUretimRoute
  AuthenticatedAdminIstasyonlarRoute: typeof AuthenticatedAdminIstasyonlarRoute
  AuthenticatedAdminKullanicilarRoute: typeof AuthenticatedAdminKullanicilarRoute
  AuthenticatedAdminMusterilerRoute: typeof AuthenticatedAdminMusterilerRoute
  AuthenticatedOperatorProvaRoute: typeof AuthenticatedOperatorProvaRoute
  AuthenticatedRotaOrderIdRoute: typeof AuthenticatedRotaOrderIdRoute
  AuthenticatedSilindirHazirlaOrderIdRoute: typeof AuthenticatedSilindirHazirlaOrderIdRoute
  AuthenticatedSilindirCylCodeRoute: typeof AuthenticatedSilindirCylCodeRoute
  AuthenticatedSiparisOrderIdRoute: typeof AuthenticatedSiparisOrderIdRoute
  AuthenticatedOperatorIndexRoute: typeof AuthenticatedOperatorIndexRoute
  AuthenticatedOperatorAktifOperationIdRoute: typeof AuthenticatedOperatorAktifOperationIdRoute
  AuthenticatedOperatorIsStepIdRoute: typeof AuthenticatedOperatorIsStepIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArsivRoute: AuthenticatedArsivRoute,
  AuthenticatedDepoRoute: AuthenticatedDepoRoute,
  AuthenticatedKaliteRoute: AuthenticatedKaliteRoute,
  AuthenticatedKayitlarRoute: AuthenticatedKayitlarRoute,
  AuthenticatedKuyrukRoute: AuthenticatedKuyrukRoute,
  AuthenticatedMuhasebeRoute: AuthenticatedMuhasebeRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedSevkiyatRoute: AuthenticatedSevkiyatRoute,
  AuthenticatedSiparislerRoute: AuthenticatedSiparislerRoute,
  AuthenticatedUretimRoute: AuthenticatedUretimRoute,
  AuthenticatedAdminIstasyonlarRoute: AuthenticatedAdminIstasyonlarRoute,
  AuthenticatedAdminKullanicilarRoute: AuthenticatedAdminKullanicilarRoute,
  AuthenticatedAdminMusterilerRoute: AuthenticatedAdminMusterilerRoute,
  AuthenticatedOperatorProvaRoute: AuthenticatedOperatorProvaRoute,
  AuthenticatedRotaOrderIdRoute: AuthenticatedRotaOrderIdRoute,
  AuthenticatedSilindirHazirlaOrderIdRoute:
    AuthenticatedSilindirHazirlaOrderIdRoute,
  AuthenticatedSilindirCylCodeRoute: AuthenticatedSilindirCylCodeRoute,
  AuthenticatedSiparisOrderIdRoute: AuthenticatedSiparisOrderIdRoute,
  AuthenticatedOperatorIndexRoute: AuthenticatedOperatorIndexRoute,
  AuthenticatedOperatorAktifOperationIdRoute:
    AuthenticatedOperatorAktifOperationIdRoute,
  AuthenticatedOperatorIsStepIdRoute: AuthenticatedOperatorIsStepIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGrafikTemizlikRoute: ApiPublicGrafikTemizlikRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
